# helm-demo/values.yaml

replicaCount: 1

image:
  repository: petartotev/demonetkubernetes
  tag: v1.0  # Replace with the desired tag
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  downscaleStabilizationDurationSeconds: 60