# helm-demo/values.yaml

replicaCount: 1

image:
  repository: petartotev/demonetkubernetes
  tag: latest  # Replace with the desired tag
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50
  downscaleStabilizationDurationSeconds: 60

dependencies:
  - name: redis
    version: any # Use the version of the Redis Helm chart you've installed
    repository: https://charts.bitnami.com/bitnami