# helm-chart/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  database-password: dGhpcy1pcy1teS1zdXBlci1zZWNyZXQtY29ubmVjdGlvbi1zdHJpbmc= # BASE64_ENCODED_PASSWORD